[app]
host = "0.0.0.0"
key = "this is your app key"
name = "demo"
port = "8050"

# GRANT ALL PRIVILEGES ON test.* TO 'demo'@'%' IDENTIFIED BY '123456';
[mysql]
database = "test"
host = "127.0.0.1"
password = "123456"
port = "3306"
username = "demo"

[log]
# DebugLevel: "debug",
# InfoLevel:  "info",
# WarnLevel:  "warning",
# ErrorLevel: "error",
# FatalLevel: "fatal",
# PanicLevel: "panic",
dir = "logs"
format = "text"
level = "debug"
to = "stdout"
