// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package book

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseCatalogFromString Parse Catalog from string
func ParseCatalogFromString(str string) (Catalog, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := Catalog_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown Catalog: %s", str)
	}

	return Catalog(v), nil
}

// Equal type compare
func (t Catalog) Equal(target Catalog) bool {
	return t == target
}

// IsIn todo
func (t Catalog) IsIn(targets ...Catalog) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t Catalog) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *Catalog) UnmarshalJSON(b []byte) error {
	ins, err := ParseCatalogFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
